<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($category){
            $category->allSubCategories()->delete();
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_parent');
    }


    public function subCategories()
    {
        return $this->hasMany(Category::class, 'category_parent' );
    }

    public function allSubCategories()
    {
        return $this->subCategories()->with('allSubCategories')->orderBy('order');
    }

}
